### ISSUE TITLE
I added xstatic to the list ...

### ISSUE THREAD

**Issue by guettli** [python-xstatic/xstatic#1]
Hi,

I added your solution (xstatic) to the [Django and Third-Party JS List](https://github.com/guettli/django-and-third-party-js)

I hope that sooner or later the django community has an easy and simple answer to the question.

Feedback is welcome!

**Comment by guettli** [comment]
Feel free to close this issue again, I just wanted you to know about this.

**Comment by ThomasWaldmann** [comment]
thanks for notifying, yeah, it is good to have some info about the misc. options.

i noticed a wording issue in that document: "It is likely that **you** package you need was not uploaded yet."

**Comment by guettli** [comment]
Thank you for the hint. I fixed the typo in my README.
